Test pool migration script
hmcts/juror-database-migration pull request #136
Opened 2024-05-31 14:37 UTC by shankar-pankhania-hmcts

2024-06-06 11:01 UTC, CCHAPMAN01 requested changes
Please see review comments

2024-06-06 11:01 UTC, CCHAPMAN01 commented on Postgres old schema to new schema migration/test/0015 - pool/015 - pool test setup.sql
> +insert into juror.unique_pool (owner,pool_no,jurisdiction_code,return_date,next_date,no_requested,pool_total,reg_spc,pool_type,loc_code,new_request,last_update,read_only,deferrals_used,additional_sum
Add another test where only one copy of a unique pool exists and read_only  = 'Y'

2024-06-17 21:26 UTC, CCHAPMAN01 commented on Postgres old schema to new schema migration/test/0015 - pool/015 - pool test verification.sql
> +('4346','416','2024-05-04',NULL,NULL,'440','Y','2024-04-02 11:33:37.000',2,NULL,false,0,NULL);
no_requested is now always defaulted to 0 as a new migration stage - please update expected

2024-06-18 10:04 UTC, KatieHarrison1 commented on Postgres old schema to new schema migration/test/0015 - pool/015 - pool test verification.sql
> +('4346','416','2024-05-04',NULL,NULL,'440','Y','2024-04-02 11:33:37.000',2,NULL,false,0,NULL);
Value has now been updated :)

2024-06-18 12:19 UTC, merged