Test coroner pool migration script
hmcts/juror-database-migration pull request #144
Opened 2024-06-04 13:20 UTC by shankar-pankhania-hmcts

2024-06-06 07:30 UTC, CCHAPMAN01 requested changes

2024-06-06 07:30 UTC, CCHAPMAN01 commented on Postgres old schema to new schema migration/test/0018 - coroner pool/0018 - coroner pool test verification.sql
> +        phone,00
please remove '00' typo

2024-06-17 08:25 UTC, philhead1 approved these changes

2024-06-17 08:35 UTC, CCHAPMAN01 approved these changes

2024-06-17 08:35 UTC, merged