Task/jm 6842
hmcts/juror-database-migration pull request #92
Opened 2024-05-16 09:03 UTC by shankar-pankhania-hmcts

2024-05-24 13:00 UTC, CCHAPMAN01 requested changes
the migrations cript has been updated - a new stage has been added to populate another expense_rates table - please add tests for this new step as well

2024-06-17 11:43 UTC, philhead1 submitted a review, later dismissed

2024-06-17 15:04 UTC, philhead1 approved these changes

2024-06-17 21:03 UTC, CCHAPMAN01 approved these changes

2024-06-17 21:03 UTC, merged